/**
 */
#include <colormap/privateIDL/16_Level.h>
#include <colormap/privateIDL/Beach.h>
#include <colormap/privateIDL/Black-White_Linear.h>
#include <colormap/privateIDL/Blue-Green-Red-Yellow.h>
#include <colormap/privateIDL/Blue-Pastel-Red.h>
#include <colormap/privateIDL/Blue-Red.h>
#include <colormap/privateIDL/Blue-Red_2.h>
#include <colormap/privateIDL/Blue-White_Linear.h>
#include <colormap/privateIDL/Blue_Waves.h>
#include <colormap/privateIDL/CB-Accent.h>
#include <colormap/privateIDL/CB-Blues.h>
#include <colormap/privateIDL/CB-BrBG.h>
#include <colormap/privateIDL/CB-BuGn.h>
#include <colormap/privateIDL/CB-BuPu.h>
#include <colormap/privateIDL/CB-Dark2.h>
#include <colormap/privateIDL/CB-GnBu.h>
#include <colormap/privateIDL/CB-Greens.h>
#include <colormap/privateIDL/CB-Greys.h>
#include <colormap/privateIDL/CB-OrRd.h>
#include <colormap/privateIDL/CB-Oranges.h>
#include <colormap/privateIDL/CB-PRGn.h>
#include <colormap/privateIDL/CB-Paired.h>
#include <colormap/privateIDL/CB-Pastel1.h>
#include <colormap/privateIDL/CB-Pastel2.h>
#include <colormap/privateIDL/CB-PiYG.h>
#include <colormap/privateIDL/CB-PuBu.h>
#include <colormap/privateIDL/CB-PuBuGn.h>
#include <colormap/privateIDL/CB-PuOr.h>
#include <colormap/privateIDL/CB-PuRd.h>
#include <colormap/privateIDL/CB-Purples.h>
#include <colormap/privateIDL/CB-RdBu.h>
#include <colormap/privateIDL/CB-RdGy.h>
#include <colormap/privateIDL/CB-RdPu.h>
#include <colormap/privateIDL/CB-RdYiBu.h>
#include <colormap/privateIDL/CB-RdYiGn.h>
#include <colormap/privateIDL/CB-Reds.h>
#include <colormap/privateIDL/CB-Set1.h>
#include <colormap/privateIDL/CB-Set2.h>
#include <colormap/privateIDL/CB-Set3.h>
#include <colormap/privateIDL/CB-Spectral.h>
#include <colormap/privateIDL/CB-YIGn.h>
#include <colormap/privateIDL/CB-YIGnBu.h>
#include <colormap/privateIDL/CB-YIOrBr.h>
#include <colormap/privateIDL/Eos_A.h>
#include <colormap/privateIDL/Eos_B.h>
#include <colormap/privateIDL/Green-Pink.h>
#include <colormap/privateIDL/Green-Red-Blue-White.h>
#include <colormap/privateIDL/Green-White_Exponential.h>
#include <colormap/privateIDL/Green-White_Linear.h>
#include <colormap/privateIDL/Hardcandy.h>
#include <colormap/privateIDL/Haze.h>
#include <colormap/privateIDL/Hue_Sat_Lightness_1.h>
#include <colormap/privateIDL/Hue_Sat_Lightness_2.h>
#include <colormap/privateIDL/Hue_Sat_Value_1.h>
#include <colormap/privateIDL/Hue_Sat_Value_2.h>
#include <colormap/privateIDL/Mac_Style.h>
#include <colormap/privateIDL/Nature.h>
#include <colormap/privateIDL/Ocean.h>
#include <colormap/privateIDL/Pastels.h>
#include <colormap/privateIDL/Peppermint.h>
#include <colormap/privateIDL/Plasma.h>
#include <colormap/privateIDL/Prism.h>
#include <colormap/privateIDL/Purple-Red+Stripes.h>
#include <colormap/privateIDL/Rainbow+Black.h>
#include <colormap/privateIDL/Rainbow+White.h>
#include <colormap/privateIDL/Rainbow.h>
#include <colormap/privateIDL/Rainbow_18.h>
#include <colormap/privateIDL/Rainbow_2.h>
#include <colormap/privateIDL/Red-Purple.h>
#include <colormap/privateIDL/Red_Temperature.h>
#include <colormap/privateIDL/Standard_Gamma-II.h>
#include <colormap/privateIDL/Steps.h>
#include <colormap/privateIDL/Stern_Special.h>
#include <colormap/privateIDL/Volcano.h>
#include <colormap/privateIDL/Waves.h>
#include <colormap/privateMATLAB/autumn.h>
#include <colormap/privateMATLAB/bone.h>
#include <colormap/privateMATLAB/cool.h>
#include <colormap/privateMATLAB/copper.h>
#include <colormap/privateMATLAB/hot.h>
#include <colormap/privateMATLAB/hsv.h>
#include <colormap/privateMATLAB/jet.h>
#include <colormap/privateMATLAB/parula.h>
#include <colormap/privateMATLAB/pink.h>
#include <colormap/privateMATLAB/spring.h>
#include <colormap/privateMATLAB/summer.h>
#include <colormap/privateMATLAB/winter.h>
#include <colormap/privatekbinani/altitude.h>
#include <colormap/privatetransform/apricot.h>
#include <colormap/privatetransform/carnation.h>
#include <colormap/privatetransform/ether.h>
#include <colormap/privatetransform/grayscale_banded.h>
#include <colormap/privatetransform/hot_metal.h>
#include <colormap/privatetransform/lava_waves.h>
#include <colormap/privatetransform/malachite.h>
#include <colormap/privatetransform/morning_glory.h>
#include <colormap/privatetransform/peanut_butter_and_jerry.h>
#include <colormap/privatetransform/purple_haze.h>
#include <colormap/privatetransform/rainbow.h>
#include <colormap/privatetransform/rose.h>
#include <colormap/privatetransform/saturn.h>
#include <colormap/privatetransform/seismic.h>
#include <colormap/privatetransform/space.h>
#include <colormap/privatetransform/supernova.h>
