/**
 */
#include <colormap/private/IDL/16_Level.h>
#include <colormap/private/IDL/Beach.h>
#include <colormap/private/IDL/Black-White_Linear.h>
#include <colormap/private/IDL/Blue-Green-Red-Yellow.h>
#include <colormap/private/IDL/Blue-Pastel-Red.h>
#include <colormap/private/IDL/Blue-Red.h>
#include <colormap/private/IDL/Blue-Red_2.h>
#include <colormap/private/IDL/Blue-White_Linear.h>
#include <colormap/private/IDL/Blue_Waves.h>
#include <colormap/private/IDL/CB-Accent.h>
#include <colormap/private/IDL/CB-Blues.h>
#include <colormap/private/IDL/CB-BrBG.h>
#include <colormap/private/IDL/CB-BuGn.h>
#include <colormap/private/IDL/CB-BuPu.h>
#include <colormap/private/IDL/CB-Dark2.h>
#include <colormap/private/IDL/CB-GnBu.h>
#include <colormap/private/IDL/CB-Greens.h>
#include <colormap/private/IDL/CB-Greys.h>
#include <colormap/private/IDL/CB-OrRd.h>
#include <colormap/private/IDL/CB-Oranges.h>
#include <colormap/private/IDL/CB-PRGn.h>
#include <colormap/private/IDL/CB-Paired.h>
#include <colormap/private/IDL/CB-Pastel1.h>
#include <colormap/private/IDL/CB-Pastel2.h>
#include <colormap/private/IDL/CB-PiYG.h>
#include <colormap/private/IDL/CB-PuBu.h>
#include <colormap/private/IDL/CB-PuBuGn.h>
#include <colormap/private/IDL/CB-PuOr.h>
#include <colormap/private/IDL/CB-PuRd.h>
#include <colormap/private/IDL/CB-Purples.h>
#include <colormap/private/IDL/CB-RdBu.h>
#include <colormap/private/IDL/CB-RdGy.h>
#include <colormap/private/IDL/CB-RdPu.h>
#include <colormap/private/IDL/CB-RdYiBu.h>
#include <colormap/private/IDL/CB-RdYiGn.h>
#include <colormap/private/IDL/CB-Reds.h>
#include <colormap/private/IDL/CB-Set1.h>
#include <colormap/private/IDL/CB-Set2.h>
#include <colormap/private/IDL/CB-Set3.h>
#include <colormap/private/IDL/CB-Spectral.h>
#include <colormap/private/IDL/CB-YIGn.h>
#include <colormap/private/IDL/CB-YIGnBu.h>
#include <colormap/private/IDL/CB-YIOrBr.h>
#include <colormap/private/IDL/Eos_A.h>
#include <colormap/private/IDL/Eos_B.h>
#include <colormap/private/IDL/Green-Pink.h>
#include <colormap/private/IDL/Green-Red-Blue-White.h>
#include <colormap/private/IDL/Green-White_Exponential.h>
#include <colormap/private/IDL/Green-White_Linear.h>
#include <colormap/private/IDL/Hardcandy.h>
#include <colormap/private/IDL/Haze.h>
#include <colormap/private/IDL/Hue_Sat_Lightness_1.h>
#include <colormap/private/IDL/Hue_Sat_Lightness_2.h>
#include <colormap/private/IDL/Hue_Sat_Value_1.h>
#include <colormap/private/IDL/Hue_Sat_Value_2.h>
#include <colormap/private/IDL/Mac_Style.h>
#include <colormap/private/IDL/Nature.h>
#include <colormap/private/IDL/Ocean.h>
#include <colormap/private/IDL/Pastels.h>
#include <colormap/private/IDL/Peppermint.h>
#include <colormap/private/IDL/Plasma.h>
#include <colormap/private/IDL/Prism.h>
#include <colormap/private/IDL/Purple-Red+Stripes.h>
#include <colormap/private/IDL/Rainbow+Black.h>
#include <colormap/private/IDL/Rainbow+White.h>
#include <colormap/private/IDL/Rainbow.h>
#include <colormap/private/IDL/Rainbow_18.h>
#include <colormap/private/IDL/Rainbow_2.h>
#include <colormap/private/IDL/Red-Purple.h>
#include <colormap/private/IDL/Red_Temperature.h>
#include <colormap/private/IDL/Standard_Gamma-II.h>
#include <colormap/private/IDL/Steps.h>
#include <colormap/private/IDL/Stern_Special.h>
#include <colormap/private/IDL/Volcano.h>
#include <colormap/private/IDL/Waves.h>
#include <colormap/private/MATLAB/autumn.h>
#include <colormap/private/MATLAB/bone.h>
#include <colormap/private/MATLAB/cool.h>
#include <colormap/private/MATLAB/copper.h>
#include <colormap/private/MATLAB/hot.h>
#include <colormap/private/MATLAB/hsv.h>
#include <colormap/private/MATLAB/jet.h>
#include <colormap/private/MATLAB/parula.h>
#include <colormap/private/MATLAB/pink.h>
#include <colormap/private/MATLAB/spring.h>
#include <colormap/private/MATLAB/summer.h>
#include <colormap/private/MATLAB/winter.h>
#include <colormap/private/kbinani/altitude.h>
#include <colormap/private/transform/apricot.h>
#include <colormap/private/transform/carnation.h>
#include <colormap/private/transform/ether.h>
#include <colormap/private/transform/grayscale_banded.h>
#include <colormap/private/transform/hot_metal.h>
#include <colormap/private/transform/lava_waves.h>
#include <colormap/private/transform/malachite.h>
#include <colormap/private/transform/morning_glory.h>
#include <colormap/private/transform/peanut_butter_and_jerry.h>
#include <colormap/private/transform/purple_haze.h>
#include <colormap/private/transform/rainbow.h>
#include <colormap/private/transform/rose.h>
#include <colormap/private/transform/saturn.h>
#include <colormap/private/transform/seismic.h>
#include <colormap/private/transform/space.h>
#include <colormap/private/transform/supernova.h>
